const state={roundCode:new URLSearchParams(location.search).get('round')||'cashflow-01',round:null,step:1,clientRequestId:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`};
const $=s=>document.querySelector(s);
const roundCacheKey=()=>`cashflow_round:${state.roundCode}`;
async function api(action,payload=null){const opt=payload?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})}:{};const url=payload?'/api/backend':`/api/backend?action=${encodeURIComponent(action)}&roundCode=${encodeURIComponent(state.roundCode)}`;const r=await fetch(url,opt);const data=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||data.ok===false)throw Object.assign(new Error(data.message||data.error||'เกิดข้อผิดพลาด'),{data,status:r.status});return data}
function setText(id,value){const el=$(id);if(el)el.textContent=value||'—'}
function renderRound(round){if(!round)return;state.round=round;setText('#eventDate',round.event_date_label||round.event_date);setText('#eventTime',round.start_time?`เริ่ม ${round.start_time} น.`:'—');const loc=$('#eventLocation');loc.textContent=round.location_name||'—';if(round.location_url){loc.append(' · ');const a=document.createElement('a');a.href=round.location_url;a.target='_blank';a.rel='noopener';a.textContent='ดูแผนที่ →';loc.append(a)}$('#registerMeta').textContent=[round.location_name,round.event_date_label||round.event_date,round.start_time&&`เริ่ม ${round.start_time} น.`].filter(Boolean).join(' · ');const open=['Open','Full'].includes(round.status);$('#startBtn').disabled=!open;if(!open){$('#eventStatusTitle').textContent='ปิดรับใบสมัครแล้ว';$('#eventStatusText').textContent=`สถานะรอบนี้: ${round.status}`}else{$('#eventStatusTitle').textContent='สมัครแล้วรอทีมงานยืนยันสิทธิ์';$('#eventStatusText').textContent='ทีมงานจะตรวจใบสมัครและส่งอีเมลเมื่อได้รับการอนุมัติ'}}
function readRoundCache(){try{const raw=localStorage.getItem(roundCacheKey());if(!raw)return null;const x=JSON.parse(raw);if(!x||Date.now()-Number(x.savedAt||0)>10*60*1000)return null;return x.round}catch{return null}}
function saveRoundCache(round){try{localStorage.setItem(roundCacheKey(),JSON.stringify({savedAt:Date.now(),round}))}catch{}}
async function loadRound(){const cached=readRoundCache();if(cached)renderRound(cached);try{const data=await api('publicRound');renderRound(data.round);saveRoundCache(data.round);$('#eventError').classList.add('hidden')}catch(err){if(!cached){$('#eventError').textContent=err.status===503?'ระบบฐานข้อมูลยังตั้งค่าไม่ครบ กรุณาลองใหม่ภายหลัง':err.message;$('#eventError').classList.remove('hidden');$('#startBtn').disabled=true}}}
function showRegister(){if(!state.round)return;$('#eventView').classList.add('hidden');$('#registerView').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}function showEvent(){$('#registerView').classList.add('hidden');$('#eventView').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
function validateStep1(){let ok=true;document.querySelectorAll('#step1 .field[data-required]').forEach(field=>{const input=field.querySelector('input,select');const valid=input.checkValidity()&&input.value.trim()!=='';field.classList.toggle('invalid',!valid);if(!valid&&ok){input.focus();ok=false}});return ok}
document.querySelectorAll('#step1 input,#step1 select').forEach(el=>{['input','change'].forEach(ev=>el.addEventListener(ev,()=>el.closest('.field').classList.remove('invalid'))) });
function setLoading(on){const b=$('#regAction');b.disabled=on;b.textContent=on?'กำลังบันทึก…':state.step===1?'ถัดไป':state.step===2?'ส่งใบสมัคร':'กลับหน้ากิจกรรม'}
async function next(){if(state.step===1){if(!validateStep1())return;$('#step1').classList.remove('active');$('#step2').classList.add('active');$('#progress2').classList.add('on');$('#stepLabel').textContent='Step 2/2';$('#regHelp').textContent='ตรวจข้อมูลก่อนส่ง';state.step=2;setLoading(false);scrollTo({top:0,behavior:'smooth'});return}if(state.step===3){showEvent();return}setLoading(true);$('#submitError').classList.add('hidden');const fd=new FormData($('#regForm'));try{const data=await api('register',{roundCode:state.roundCode,clientRequestId:state.clientRequestId,data:{full_name:fd.get('fullname'),nickname:fd.get('nickname'),age_range:fd.get('age'),phone:fd.get('phone'),email:fd.get('email'),money_style:fd.get('moneyStyle')||'',money_goal:fd.get('moneyGoal')||''}});$('#step2').classList.remove('active');$('#pendingState').classList.add('active');$('#stepLabel').textContent='ส่งแล้ว';$('#regHelp').textContent='ระบบรับข้อมูลแล้ว · Email ยืนยันใบสมัครจะส่งอัตโนมัติ';$('#referenceCode').textContent=`Reference: ${data.registration.reference_code}`;if(data.duplicate_warning){$('#duplicateNotice').textContent='พบข้อมูลติดต่อที่เคยสมัครมาก่อน แต่ระบบรับใบสมัครครั้งนี้ไว้ตามปกติ';$('#duplicateNotice').classList.remove('hidden')}state.step=3;setLoading(false)}catch(err){$('#submitError').textContent=err.message;$('#submitError').classList.remove('hidden');setLoading(false)}}
$('#startBtn').addEventListener('click',showRegister);$('#backToEvent').addEventListener('click',showEvent);$('#regAction').addEventListener('click',next);loadRound();