const state={token:sessionStorage.getItem('cashflow_admin_token')||'',roundCode:'cashflow-01',registrations:[],rounds:[],filter:'Pending',stream:null,scanning:false,refreshTimer:null,lastSync:0};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const cacheKey=()=>`cashflow_admin_snapshot:${state.roundCode}`;

async function api(action,payload={}){const r=await fetch('/api/backend',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,token:state.token,...payload})});const data=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||data.ok===false){const e=new Error(data.message||data.error||'เกิดข้อผิดพลาด');e.status=r.status;e.data=data;throw e}return data}
function showLogin(msg=''){stopScanner();stopAutoRefresh();$('#loginView').classList.remove('hidden');$('#adminView').classList.add('hidden');if(msg){$('#loginError').textContent=msg;$('#loginError').classList.remove('hidden')}}
function showAdmin(){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');startAutoRefresh()}

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{const data=await api('adminLogin',{password:$('#adminPassword').value});state.token=data.token;sessionStorage.setItem('cashflow_admin_token',state.token);$('#adminPassword').value='';showAdmin();await loadAll({useCache:true})}catch(err){showLogin(err.message)}});
$('#logoutBtn').addEventListener('click',async()=>{try{await api('adminLogout')}catch{}sessionStorage.removeItem('cashflow_admin_token');state.token='';showLogin()});

function restoreSnapshot(){try{const raw=sessionStorage.getItem(cacheKey());if(!raw)return false;const s=JSON.parse(raw);if(!s||Date.now()-Number(s.savedAt||0)>10*60*1000)return false;applySnapshot(s);return true}catch{return false}}
function saveSnapshot(round,stats){try{sessionStorage.setItem(cacheKey(),JSON.stringify({savedAt:Date.now(),round,stats,registrations:state.registrations,rounds:state.rounds}))}catch{}}
function applySnapshot(s){state.registrations=s.registrations||[];state.rounds=s.rounds||[];if(s.round?.round_code)state.roundCode=s.round.round_code;renderHeader(s.round||{});renderStats(s.stats||computeStats());renderApplicants();renderRounds()}
function renderHeader(round){$('#adminRoundMeta').textContent=[round?.title,round?.event_date_label||round?.event_date,round?.location_name].filter(Boolean).join(' · ')}

async function fetchBootstrap(){try{return await api('adminBootstrap',{roundCode:state.roundCode})}catch(err){if(err.status===401)throw err;const [dash,rounds]=await Promise.all([api('adminDashboard',{roundCode:state.roundCode}),api('listRounds')]);return {...dash,rounds:rounds.rounds||[]}}}
async function loadAll({silent=false,useCache=false}={}){if(useCache)restoreSnapshot();if(!silent){$('#applicantError').classList.add('hidden')}try{const data=await fetchBootstrap();state.registrations=data.registrations||[];state.rounds=data.rounds||[];state.roundCode=data.round?.round_code||state.roundCode;state.lastSync=Date.now();renderHeader(data.round||{});renderStats(data.stats||computeStats());renderApplicants();renderRounds();saveSnapshot(data.round||{},data.stats||computeStats())}catch(err){if(err.status===401||err.data?.error==='unauthorized'){showLogin('Session หมดอายุ กรุณาเข้าสู่ระบบใหม่');return}if(!silent){$('#applicantError').textContent=err.message;$('#applicantError').classList.remove('hidden')}}}
function startAutoRefresh(){stopAutoRefresh();state.refreshTimer=setInterval(()=>{if(document.visibilityState==='visible'&&state.token)loadAll({silent:true})},15000)}
function stopAutoRefresh(){if(state.refreshTimer){clearInterval(state.refreshTimer);state.refreshTimer=null}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.token)loadAll({silent:true})});

function computeStats(){return {total:state.registrations.length,pending:state.registrations.filter(r=>r.status==='Pending').length,approved:state.registrations.filter(r=>r.status==='Approved').length,waitlist:state.registrations.filter(r=>r.status==='Waitlist').length,rejected:state.registrations.filter(r=>r.status==='Rejected').length,checked_in:state.registrations.filter(r=>!!r.checked_in_at).length}}
function renderStats(s){$('#statTotal').textContent=s.total||0;$('#statPending').textContent=s.pending||0;$('#statApproved').textContent=s.approved||0;$('#statChecked').textContent=s.checked_in||0}
function patchRegistration(updated){const i=state.registrations.findIndex(r=>r.registration_id===updated.registration_id);if(i>=0)state.registrations[i]={...state.registrations[i],...updated};renderStats(computeStats());renderApplicants();saveSnapshot({},computeStats())}

function renderApplicants(){const q=$('#searchInput').value.trim().toLowerCase();const list=state.registrations.filter(r=>(state.filter==='ALL'||r.status===state.filter)&&(!q||[r.full_name,r.nickname,r.phone,r.email,r.reference_code].some(v=>String(v||'').toLowerCase().includes(q))));$('#applicantList').innerHTML=list.length?list.map(r=>`<article class="applicant"><div class="applicant-top"><div><h3>${esc(r.full_name)} (${esc(r.nickname)})</h3><p>${esc(r.age_range)} · ${esc(r.phone)} · ${esc(r.email)} · ${esc(r.reference_code)}</p></div><span class="badge ${esc(r.status)}">${esc(r.status)}</span></div><div class="answer">${r.money_style?`สไตล์: ${esc(r.money_style)}<br>`:''}${r.money_goal?`อยากเข้าใจ: ${esc(r.money_goal)}`:''}${r.checked_in_at?`<br>Check-in: ${esc(r.checked_in_at)}`:''}</div><div class="admin-actions">${r.status!=='Approved'?`<button class="approve" data-action="Approved" data-id="${esc(r.registration_id)}">Approve</button>`:''}${r.status!=='Waitlist'?`<button class="secondary" data-action="Waitlist" data-id="${esc(r.registration_id)}">Waitlist</button>`:''}${r.status!=='Rejected'?`<button class="secondary danger" data-action="Rejected" data-id="${esc(r.registration_id)}">Reject</button>`:''}${r.status==='Approved'&&!r.checked_in_at?`<button class="secondary" data-checkin="${esc(r.registration_id)}">Check-in</button>`:''}</div></article>`).join(''):'<div class="notice">ไม่พบรายการในตัวกรองนี้</div>';document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>changeStatus(b.dataset.id,b.dataset.action)));document.querySelectorAll('[data-checkin]').forEach(b=>b.addEventListener('click',()=>checkIn({registrationId:b.dataset.checkin})))}
async function changeStatus(id,status){if(status==='Rejected'&&!confirm('ยืนยัน Reject ใบสมัครนี้?'))return;const btn=document.querySelector(`[data-action="${CSS.escape(status)}"][data-id="${CSS.escape(id)}"]`);if(btn){btn.disabled=true;btn.textContent='กำลังบันทึก…'}try{const data=await api('updateRegistrationStatus',{registrationId:id,status,roundCode:state.roundCode});patchRegistration(data.registration);loadAll({silent:true})}catch(err){alert(err.message);if(btn){btn.disabled=false;btn.textContent=status==='Approved'?'Approve':status}}}

$('#searchInput').addEventListener('input',renderApplicants);$('#refreshBtn').addEventListener('click',()=>loadAll());document.querySelectorAll('.filter-chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.status;renderApplicants()}));
document.querySelectorAll('.admin-nav [data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.admin-nav [data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');['applicants','rounds','checkin'].forEach(t=>$(`#tab-${t}`).classList.toggle('hidden',t!==b.dataset.tab));if(b.dataset.tab!=='checkin')stopScanner()}));

function renderRounds(){$('#roundList').innerHTML=state.rounds.map(r=>`<div class="round-item"><strong>${esc(r.title)}</strong><div>${esc(r.round_code)} · ${esc(r.status)} · ${esc(r.event_date_label||r.event_date||'ยังไม่ระบุวัน')}</div><button class="secondary" data-edit-round="${esc(r.round_id)}">แก้ไข</button></div>`).join('')||'<div class="notice">ยังไม่มีรอบ</div>';document.querySelectorAll('[data-edit-round]').forEach(b=>b.addEventListener('click',()=>editRound(b.dataset.editRound)))}
function editRound(id){const r=state.rounds.find(x=>x.round_id===id);if(!r)return;$('#roundFormTitle').textContent='แก้ไขรอบ';$('#roundId').value=r.round_id||'';$('#roundCode').value=r.round_code||'';$('#roundTitle').value=r.title||'';$('#roundDate').value=r.event_date||'';$('#roundDateLabel').value=r.event_date_label||'';$('#roundStart').value=r.start_time||'';$('#roundEnd').value=r.end_time||'';$('#roundLocation').value=r.location_name||'';$('#roundLocationUrl').value=r.location_url||'';$('#roundStatus').value=r.status||'Draft';$('#capacityEnabled').checked=String(r.capacity_enabled).toLowerCase()==='true';$('#approvalCapacity').value=r.approval_capacity||30;scrollTo({top:0,behavior:'smooth'})}
$('#roundForm').addEventListener('submit',async e=>{e.preventDefault();$('#roundError').classList.add('hidden');const round={round_id:$('#roundId').value,round_code:$('#roundCode').value.trim(),title:$('#roundTitle').value.trim(),event_date:$('#roundDate').value,event_date_label:$('#roundDateLabel').value.trim(),start_time:$('#roundStart').value,end_time:$('#roundEnd').value,location_name:$('#roundLocation').value.trim(),location_url:$('#roundLocationUrl').value.trim(),status:$('#roundStatus').value,capacity_enabled:$('#capacityEnabled').checked,approval_capacity:Number($('#approvalCapacity').value||30),public_seat_display:'จำนวนจำกัด'};const submit=e.submitter;const old=submit?.textContent;if(submit){submit.disabled=true;submit.textContent='กำลังบันทึก…'}try{const data=await api('saveRound',{round});const i=state.rounds.findIndex(r=>r.round_id===data.round.round_id);if(i>=0)state.rounds[i]=data.round;else state.rounds.unshift(data.round);renderRounds();$('#roundForm').reset();$('#roundId').value='';$('#roundFormTitle').textContent='สร้างรอบใหม่';loadAll({silent:true})}catch(err){$('#roundError').textContent=err.message;$('#roundError').classList.remove('hidden')}finally{if(submit){submit.disabled=false;submit.textContent=old}}});

async function checkIn(payload){try{const data=await api('checkIn',{roundCode:state.roundCode,...payload});$('#checkResult').innerHTML=`<div class="notice success"><strong>Check-in สำเร็จ</strong><br>${esc(data.registration.full_name)} (${esc(data.registration.nickname)})<br>${esc(data.registration.reference_code)}</div>`;stopScanner();patchRegistration(data.registration);loadAll({silent:true})}catch(err){$('#checkResult').innerHTML=`<div class="notice error">${esc(err.message)}</div>`}}
async function searchCheckin(){const q=$('#checkQuery').value.trim();if(q.length<2){$('#checkResult').innerHTML='<div class="notice">พิมพ์อย่างน้อย 2 ตัวอักษร หรือใช้ Reference / เบอร์โทร</div>';return}try{const data=await api('checkinSearch',{roundCode:state.roundCode,query:q});const matches=data.matches||[];$('#checkResult').innerHTML=matches.length?matches.map(r=>`<div class="applicant"><div class="applicant-top"><div><h3>${esc(r.full_name)} (${esc(r.nickname)})</h3><p>${esc(r.phone)} · ${esc(r.reference_code)}</p></div><span class="badge ${esc(r.status)}">${r.checked_in_at?'Checked-in':'Approved'}</span></div><div class="admin-actions">${r.checked_in_at?`<span class="cta-help">Check-in แล้ว ${esc(r.checked_in_at)}</span>`:`<button class="approve" data-check-result="${esc(r.registration_id)}">ยืนยัน Check-in</button>`}</div></div>`).join(''):'<div class="notice">ไม่พบผู้ได้รับอนุมัติที่ตรงกับคำค้น</div>';document.querySelectorAll('[data-check-result]').forEach(b=>b.addEventListener('click',()=>checkIn({registrationId:b.dataset.checkResult})))}catch(err){$('#checkResult').innerHTML=`<div class="notice error">${esc(err.message)}</div>`}}
$('#checkSearchBtn').addEventListener('click',searchCheckin);$('#checkQuery').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchCheckin()}});
function parseQr(raw){if(raw.startsWith('CF:'))return raw.slice(3);try{const u=new URL(raw);return u.searchParams.get('token')||raw}catch{return raw}}
async function startScanner(){if(!('BarcodeDetector'in window)){alert('เบราว์เซอร์นี้ไม่รองรับ QR scanner ให้ใช้ช่องค้นหาแทน');return}try{state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});const v=$('#scannerVideo');v.srcObject=state.stream;v.classList.remove('hidden');$('#scanBox span')?.classList.add('hidden');await v.play();state.scanning=true;const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!state.scanning)return;try{const codes=await detector.detect(v);if(codes[0]?.rawValue){state.scanning=false;await checkIn({qrToken:parseQr(codes[0].rawValue)});return}}catch{}requestAnimationFrame(loop)};loop()}catch(err){alert('เปิดกล้องไม่ได้: '+err.message)}}
function stopScanner(){state.scanning=false;if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}const v=$('#scannerVideo');if(v){v.pause();v.srcObject=null;v.classList.add('hidden')}const label=$('#scanBox span');if(label)label.classList.remove('hidden')}
$('#scanBtn').addEventListener('click',startScanner);
if(state.token){showAdmin();loadAll({useCache:true})}else showLogin();