const SHEETS={REG:'Registrations',ROUNDS:'Rounds',SETTINGS:'Settings',AUDIT:'AuditLog'};
const REG_HEADERS=['registration_id','round_code','submitted_at','full_name','nickname','age_range','phone','email','money_style','money_goal','status','reference_code','qr_token','approved_at','checked_in_at','admin_note','updated_at','client_request_id','approval_email_sent_at'];
const ROUND_HEADERS=['round_id','round_code','title','event_date','event_date_label','start_time','end_time','location_name','location_url','status','capacity_enabled','approval_capacity','public_seat_display','created_at','updated_at'];

function onOpen(){SpreadsheetApp.getUi().createMenu('Cashflow System').addItem('ตรวจ/เตรียมฐานข้อมูล','setupCashflow').addItem('ตั้งรหัส Admin','setupAdminPassword').addToUi();}
function setupCashflow(){const ss=SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw new Error('กรุณาเปิด Apps Script จาก Google Sheet นี้');PropertiesService.getScriptProperties().setProperty('SPREADSHEET_ID',ss.getId());ensureSheet_(ss,SHEETS.REG,REG_HEADERS);ensureSheet_(ss,SHEETS.ROUNDS,ROUND_HEADERS);ensureSheet_(ss,SHEETS.SETTINGS,['key','value','description']);ensureSheet_(ss,SHEETS.AUDIT,['timestamp','actor','action','round_code','registration_id','detail']);SpreadsheetApp.getUi().alert('ฐานข้อมูลพร้อมแล้ว');}
function setupAdminPassword(){const ui=SpreadsheetApp.getUi();const r=ui.prompt('ตั้งรหัส Admin','ใช้รหัสที่คาดเดายากอย่างน้อย 8 ตัวอักษร',ui.ButtonSet.OK_CANCEL);if(r.getSelectedButton()!==ui.Button.OK)return;const p=r.getResponseText();if(!p||p.length<8)throw new Error('รหัสต้องยาวอย่างน้อย 8 ตัวอักษร');PropertiesService.getScriptProperties().setProperty('ADMIN_PASSWORD_HASH',sha256Hex_(p));ui.alert('ตั้งรหัส Admin แล้ว');}
function doGet(e){try{const a=(e&&e.parameter&&e.parameter.action)||'health';if(a==='health')return json_({ok:true,configured:isConfigured_()});if(a==='publicRound')return json_({ok:true,...publicRound_((e.parameter||{}).roundCode)});return json_({ok:false,error:'unknown_action'},400)}catch(err){return json_({ok:false,error:'server_error',message:err.message},500)}}
function doPost(e){try{const body=JSON.parse((e.postData&&e.postData.contents)||'{}');const a=body.action;let out;if(a==='register')out=register_(body);else if(a==='adminLogin')out=adminLogin_(body.password);else if(a==='adminLogout')out=adminLogout_(body.token);else if(a==='adminDashboard'){requireAdmin_(body.token);out=adminDashboard_(body.roundCode)}else if(a==='updateRegistrationStatus'){requireAdmin_(body.token);out=updateRegistrationStatus_(body)}else if(a==='checkIn'){requireAdmin_(body.token);out=checkIn_(body)}else if(a==='resendApprovalEmail'){requireAdmin_(body.token);out=resendApprovalEmail_(body)}else if(a==='listRounds'){requireAdmin_(body.token);out={rounds:listRows_(SHEETS.ROUNDS)}}else if(a==='saveRound'){requireAdmin_(body.token);out=saveRound_(body.round)}else throw new Error('unknown_action');return json_({ok:true,...out})}catch(err){const code=err.message==='unauthorized'?401:400;return json_({ok:false,error:err.message==='unauthorized'?'unauthorized':'request_failed',message:userMessage_(err.message)},code)}}
function userMessage_(m){const map={unauthorized:'Session ไม่ถูกต้องหรือหมดอายุ',admin_not_configured:'ยังไม่ได้ตั้งรหัส Admin',round_not_found:'ไม่พบรอบกิจกรรม',round_closed:'รอบนี้ปิดรับใบสมัครแล้ว',capacity_full:'จำนวนอนุมัติเต็มแล้ว',registration_not_found:'ไม่พบผู้สมัคร',invalid_email:'Email ไม่ถูกต้อง',invalid_phone:'เบอร์โทรไม่ถูกต้อง',missing_required_fields:'กรอกข้อมูลที่จำเป็นไม่ครบ',duplicate_round_code:'Round code ซ้ำ',backend_not_configured:'Backend ยังตั้งค่าไม่ครบ'};return map[m]||m}
function publicRound_(code){const round=findRound_(code||getSetting_('active_round_code'));if(!round)throw new Error('round_not_found');const regs=listRows_(SHEETS.REG).filter(r=>r.round_code===round.round_code);const approved=regs.filter(r=>r.status==='Approved').length;const cap=Number(round.approval_capacity||0);return {round:{...round,approved_count:approved,remaining_seats:truthy_(round.capacity_enabled)&&cap?Math.max(0,cap-approved):null}}}
function register_(body){const d=body.data||{};const required=['full_name','nickname','age_range','phone','email'];if(required.some(k=>!clean_(d[k],k==='email'?150:120)))throw new Error('missing_required_fields');const email=clean_(d.email,150).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('invalid_email');const phone=clean_(d.phone,30);if(phone.replace(/\D/g,'').length<8)throw new Error('invalid_phone');const round=findRound_(body.roundCode||getSetting_('active_round_code'));if(!round)throw new Error('round_not_found');if(!['Open','Full'].includes(round.status))throw new Error('round_closed');const clientId=clean_(body.clientRequestId,120)||Utilities.getUuid();const lock=LockService.getScriptLock();lock.waitLock(10000);try{const existing=listRows_(SHEETS.REG).find(r=>r.client_request_id===clientId);if(existing)return {registration:publicRegistration_(existing),duplicate_warning:false,idempotent:true};const all=listRows_(SHEETS.REG);const duplicate=all.some(r=>r.round_code===round.round_code&&(normalizePhone_(r.phone)===normalizePhone_(phone)||String(r.email||'').toLowerCase()===email));const now=now_();const row={registration_id:Utilities.getUuid(),round_code:round.round_code,submitted_at:now,full_name:clean_(d.full_name,100),nickname:clean_(d.nickname,40),age_range:clean_(d.age_range,40),phone,email,money_style:clean_(d.money_style,80),money_goal:clean_(d.money_goal,500),status:'Pending',reference_code:uniqueReference_(),qr_token:Utilities.getUuid(),approved_at:'',checked_in_at:'',admin_note:'',updated_at:now,client_request_id:clientId,approval_email_sent_at:''};appendObject_(SHEETS.REG,REG_HEADERS,row);audit_('participant','register',round.round_code,row.registration_id,duplicate?'duplicate contact warning':'');return {registration:publicRegistration_(row),duplicate_warning:duplicate,idempotent:false}}finally{lock.releaseLock()}}
function adminLogin_(password){const props=PropertiesService.getScriptProperties();const expected=props.getProperty('ADMIN_PASSWORD_HASH');if(!expected)throw new Error('admin_not_configured');const cache=CacheService.getScriptCache();const fail=Number(cache.get('admin_fail_count')||0);if(fail>=10)throw new Error('ลองใหม่อีกครั้งภายหลัง');if(sha256Hex_(String(password||''))!==expected){cache.put('admin_fail_count',String(fail+1),300);throw new Error('unauthorized')}cache.remove('admin_fail_count');const token=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');cache.put('session:'+token,'admin',21600);return {token,expires_in_seconds:21600}}
function adminLogout_(token){if(token)CacheService.getScriptCache().remove('session:'+token);return {logged_out:true}}
function requireAdmin_(token){if(!token||CacheService.getScriptCache().get('session:'+token)!=='admin')throw new Error('unauthorized')}
function adminDashboard_(roundCode){const round=findRound_(roundCode||getSetting_('active_round_code'));if(!round)throw new Error('round_not_found');const regs=listRows_(SHEETS.REG).filter(r=>r.round_code===round.round_code).sort((a,b)=>String(b.submitted_at).localeCompare(String(a.submitted_at)));return {round,stats:{total:regs.length,pending:regs.filter(r=>r.status==='Pending').length,approved:regs.filter(r=>r.status==='Approved').length,waitlist:regs.filter(r=>r.status==='Waitlist').length,rejected:regs.filter(r=>r.status==='Rejected').length,checked_in:regs.filter(r=>!!r.checked_in_at).length},registrations:regs.map(adminRegistration_)} }
function updateRegistrationStatus_(body){const status=String(body.status||'');if(!['Pending','Approved','Waitlist','Rejected'].includes(status))throw new Error('invalid_status');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const ref=findRowBy_(SHEETS.REG,'registration_id',body.registrationId);if(!ref)throw new Error('registration_not_found');const reg=ref.obj;const round=findRound_(reg.round_code);if(status==='Approved'&&reg.status!=='Approved'&&truthy_(round.capacity_enabled)){const cap=Number(round.approval_capacity||0);const approved=listRows_(SHEETS.REG).filter(r=>r.round_code===round.round_code&&r.status==='Approved').length;if(cap&&approved>=cap)throw new Error('capacity_full')}const now=now_();const patch={status,updated_at:now};if(status==='Approved'&&!reg.approved_at)patch.approved_at=now;updateObjectRow_(SHEETS.REG,ref.row,patch);audit_('admin','status:'+status,reg.round_code,reg.registration_id,clean_(body.note,300));const updated={...reg,...patch};let emailSent=null,emailError='';if(status==='Approved'&&reg.status!=='Approved'){try{sendApprovalEmail_(updated,round);const sentAt=now_();updateObjectRow_(SHEETS.REG,ref.row,{approval_email_sent_at:sentAt,updated_at:sentAt});updated.approval_email_sent_at=sentAt;updated.updated_at=sentAt;emailSent=true;audit_('system','approval_email_sent',reg.round_code,reg.registration_id,'')}catch(err){emailSent=false;emailError=String(err.message||err);audit_('system','approval_email_failed',reg.round_code,reg.registration_id,emailError)}}return {registration:adminRegistration_(updated),email_sent:emailSent,email_error:emailError}}finally{lock.releaseLock()}}
function checkIn_(body){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const regs=listRows_(SHEETS.REG).filter(r=>!body.roundCode||r.round_code===body.roundCode);const q=clean_(body.query,150).toLowerCase();let reg=regs.find(r=>body.registrationId&&r.registration_id===body.registrationId)||regs.find(r=>body.qrToken&&r.qr_token===body.qrToken)||regs.find(r=>q&&(String(r.reference_code).toLowerCase()===q||normalizePhone_(r.phone)===normalizePhone_(q)))||regs.find(r=>q&&[r.full_name,r.nickname].some(v=>String(v||'').toLowerCase().includes(q)));if(!reg)throw new Error('registration_not_found');if(reg.status!=='Approved')throw new Error('ผู้สมัครยังไม่ได้รับการอนุมัติ');if(reg.checked_in_at)return {registration:adminRegistration_(reg),already_checked_in:true};const ref=findRowBy_(SHEETS.REG,'registration_id',reg.registration_id);const now=now_();updateObjectRow_(SHEETS.REG,ref.row,{checked_in_at:now,updated_at:now});audit_('admin','check_in',reg.round_code,reg.registration_id,'');reg.checked_in_at=now;reg.updated_at=now;return {registration:adminRegistration_(reg),already_checked_in:false}}finally{lock.releaseLock()}}
function resendApprovalEmail_(body){const ref=findRowBy_(SHEETS.REG,'registration_id',body.registrationId);if(!ref)throw new Error('registration_not_found');if(ref.obj.status!=='Approved')throw new Error('ผู้สมัครยังไม่ได้รับการอนุมัติ');const round=findRound_(ref.obj.round_code);try{sendApprovalEmail_(ref.obj,round);const sentAt=now_();updateObjectRow_(SHEETS.REG,ref.row,{approval_email_sent_at:sentAt,updated_at:sentAt});audit_('admin','approval_email_resent',ref.obj.round_code,ref.obj.registration_id,'');ref.obj.approval_email_sent_at=sentAt;return {registration:adminRegistration_(ref.obj),email_sent:true}}catch(err){audit_('system','approval_email_failed',ref.obj.round_code,ref.obj.registration_id,String(err.message||err));return {registration:adminRegistration_(ref.obj),email_sent:false,email_error:String(err.message||err)}}}
function saveRound_(input){const r=input||{};const code=clean_(r.round_code,60);const title=clean_(r.title,120);if(!code||!title)throw new Error('กรอก Round code และชื่อรอบ');const all=listRows_(SHEETS.ROUNDS);const duplicate=all.find(x=>x.round_code===code&&x.round_id!==r.round_id);if(duplicate)throw new Error('duplicate_round_code');const now=now_();const obj={round_id:r.round_id||Utilities.getUuid(),round_code:code,title,event_date:clean_(r.event_date,20),event_date_label:clean_(r.event_date_label,80),start_time:clean_(r.start_time,10),end_time:clean_(r.end_time,10),location_name:clean_(r.location_name,160),location_url:clean_(r.location_url,500),status:['Draft','Open','Closed','Completed','Cancelled'].includes(r.status)?r.status:'Draft',capacity_enabled:!!r.capacity_enabled,approval_capacity:Math.max(1,Number(r.approval_capacity||30)),public_seat_display:clean_(r.public_seat_display,80)||'จำนวนจำกัด',updated_at:now};if(r.round_id){const ref=findRowBy_(SHEETS.ROUNDS,'round_id',r.round_id);if(!ref)throw new Error('round_not_found');const hasRegs=listRows_(SHEETS.REG).some(x=>x.round_code===ref.obj.round_code);if(hasRegs&&ref.obj.round_code!==code)throw new Error('เปลี่ยน Round code ไม่ได้หลังมีผู้สมัครแล้ว');updateObjectRow_(SHEETS.ROUNDS,ref.row,obj)}else{obj.created_at=now;appendObject_(SHEETS.ROUNDS,ROUND_HEADERS,obj)}audit_('admin',r.round_id?'update_round':'create_round',code,'',title);return {round:obj}}
function sendApprovalEmail_(reg,round){if(!reg.email)return;const subject=`ยืนยันสิทธิ์ ${round.title||'CA$HFLOW Meetup'}`;const qrText='CF:'+reg.qr_token;const qrUrl='https://quickchart.io/qr?size=240&text='+encodeURIComponent(qrText);let cal='';if(round.event_date&&round.start_time&&round.end_time){const start=String(round.event_date).replace(/-/g,'')+'T'+String(round.start_time).replace(':','')+'00';const end=String(round.event_date).replace(/-/g,'')+'T'+String(round.end_time).replace(':','')+'00';cal='https://calendar.google.com/calendar/render?action=TEMPLATE&text='+encodeURIComponent(round.title||'CA$HFLOW Meetup')+'&dates='+start+'/'+end+'&location='+encodeURIComponent(round.location_name||'')}
const html=`<div style="font-family:Arial,sans-serif;line-height:1.6"><h2>ได้รับการอนุมัติแล้ว</h2><p>สวัสดี ${escapeHtml_(reg.nickname||reg.full_name)}</p><p>Reference: <b>${escapeHtml_(reg.reference_code)}</b></p><p>${escapeHtml_(round.event_date_label||round.event_date||'')} ${escapeHtml_(round.start_time||'')}<br>${escapeHtml_(round.location_name||'')}</p><p><img src="${qrUrl}" width="220" height="220" alt="QR Check-in"></p><p>โปรดแสดง QR นี้ที่จุด Check-in</p>${cal?`<p><a href="${cal}">Add to Google Calendar</a></p>`:''}</div>`;MailApp.sendEmail({to:reg.email,subject,htmlBody:html,name:getSetting_('confirmation_sender_name')||'CA$HFLOW Meetup'})}
function publicRegistration_(r){return {registration_id:r.registration_id,status:r.status,reference_code:r.reference_code,submitted_at:r.submitted_at}}
function adminRegistration_(r){return {registration_id:r.registration_id,round_code:r.round_code,submitted_at:r.submitted_at,full_name:r.full_name,nickname:r.nickname,age_range:r.age_range,phone:r.phone,email:r.email,money_style:r.money_style,money_goal:r.money_goal,status:r.status,reference_code:r.reference_code,approved_at:r.approved_at,checked_in_at:r.checked_in_at,admin_note:r.admin_note,updated_at:r.updated_at,approval_email_sent_at:r.approval_email_sent_at}}
function findRound_(code){return listRows_(SHEETS.ROUNDS).find(r=>r.round_code===code)||null}
function getSetting_(key){const r=listRows_(SHEETS.SETTINGS).find(x=>x.key===key);return r?r.value:''}
function listRows_(name){const sh=sheet_(name);const values=sh.getDataRange().getValues();if(values.length<2)return[];const h=values[0].map(String);return values.slice(1).filter(r=>r.some(v=>v!==''&&v!==null)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}
function findRowBy_(name,key,value){const sh=sheet_(name);const vals=sh.getDataRange().getValues();if(!vals.length)return null;const h=vals[0].map(String);const idx=h.indexOf(key);for(let i=1;i<vals.length;i++)if(String(vals[i][idx])===String(value))return{row:i+1,obj:Object.fromEntries(h.map((k,j)=>[k,vals[i][j]]))};return null}
function appendObject_(name,headers,obj){sheet_(name).appendRow(headers.map(h=>obj[h]===undefined?'':obj[h]))}
function updateObjectRow_(name,row,patch){const sh=sheet_(name);const h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);Object.entries(patch).forEach(([k,v])=>{const c=h.indexOf(k);if(c>=0)sh.getRange(row,c+1).setValue(v===undefined?'':v)})}
function sheet_(name){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');const ss=id?SpreadsheetApp.openById(id):SpreadsheetApp.getActiveSpreadsheet();if(!ss)throw new Error('backend_not_configured');const sh=ss.getSheetByName(name);if(!sh)throw new Error('backend_not_configured');return sh}
function ensureSheet_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);const first=sh.getRange(1,1,1,headers.length).getValues()[0];if(first.every(v=>v===''))sh.getRange(1,1,1,headers.length).setValues([headers]);return sh}
function audit_(actor,action,roundCode,registrationId,detail){sheet_(SHEETS.AUDIT).appendRow([now_(),actor,action,roundCode||'',registrationId||'',detail||''])}
function uniqueReference_(){const existing=new Set(listRows_(SHEETS.REG).map(r=>String(r.reference_code)));for(let i=0;i<30;i++){const code=String(Math.floor(100000+Math.random()*900000));if(!existing.has(code))return code}return String(Date.now()).slice(-6)}
function now_(){return Utilities.formatDate(new Date(),'Asia/Bangkok',"yyyy-MM-dd'T'HH:mm:ssXXX")}
function clean_(v,max){return String(v??'').trim().slice(0,max||500)}function normalizePhone_(v){return String(v||'').replace(/\D/g,'')}function truthy_(v){return v===true||String(v).toLowerCase()==='true'}
function sha256Hex_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8).map(b=>('0'+((b<0?b+256:b).toString(16))).slice(-2)).join('')}
function escapeHtml_(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isConfigured_(){const p=PropertiesService.getScriptProperties();return !!(p.getProperty('SPREADSHEET_ID')&&p.getProperty('ADMIN_PASSWORD_HASH'))}
function json_(obj,status){return ContentService.createTextOutput(JSON.stringify({...obj,http_status:status||200})).setMimeType(ContentService.MimeType.JSON)}
